---
name: "Get Repo Members"
description: "Get all members associated with a repository"
inputs:
  token:
    description: "PAT with permissions"
    required: true
  owner:
    description: "Repo owner"
    required: true
  repo:
    description: "Repo name"
    required: true
outputs:
  members:
    description: "List of members of repository"
runs:
  using: "node16"
  main: "dist/index.js"
